# Generated by Django 3.1.5 on 2021-02-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime', models.CharField(max_length=20, unique=True)),
                ('Light', models.IntegerField()),
                ('SingleUnitTruck', models.IntegerField()),
                ('ArticulatedTruck', models.IntegerField()),
                ('MotorizedVehicle', models.IntegerField()),
                ('Bycycle', models.IntegerField()),
            ],
        ),
    ]
