# Generated by Django 3.1.5 on 2021-02-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210215_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='ArticulatedTruck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='Bicycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='Light',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='MotorizedVehicle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='SingleUnitTruck',
            field=models.IntegerField(default=0),
        ),
    ]
