# Generated by Django 3.1.5 on 2021-02-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210216_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledata',
            name='Bus',
            field=models.IntegerField(default=0),
        ),
    ]
